repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: [--target-version=py36]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.5
    hooks:
      - id: prettier
